language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
  addons:
    apt:
      update: true
env:
  global:
  - secure: E/9g2O5ujcak6w1KSNqEnvi5RLwRJ/Vibd4vMDhMHcBd62QnvUxV/Rm4javI63JBt0oRWody3tvPhmiS2gN8oO3LPb6kgxuqwxlQVyBzDnTD94qMDiHJK1wDX6jxhXvcLCyxPgvqUgsHJmFOCaMTbHsxI/teysyYEC1tScV0RMardrVZNUAR7R05n1RRuDzA8bVtxyGtCJygMN9Xu7eilESeb6JcdlStZUVNFpfCKirLYBldX5C8G2K724n6K/bSHZTvxKvsaeiE/QYGZebRg1VC3FWDCZ/agb9cRcUJYJNQ1gAhq6d1wErHyd8u04upj9xTnt+q4NfMdx4wEE1f7s4JHhvDlMImXuuJbagcOWPJV0nDs59XxNnkepyRcpAfWuBm6iU01XpPMesUrqiirIn7CWyBFOi9KUqWJJdHhyKlH2hHuLUFTTXqWE3A4AEdqQuNFO38Po2bHSpNEWo8SHzZQG5I02psaddF0o+nL3/KzzQSaSOcOoZHAPv/chb3S33CJ9+WvVjUkta3uco8Xwi8P6fmJCtOsN7OGzOwICCPvzLPjegX2Te0aJcGNpnmVfCvG/YE+TMTTEa3FoZEvx+0jvuKLA9Z9KyEDmxzxCZ7kTECyCGHClKEv4JbfbFpCpssm5xptz5NHwGQcE4//37oR6T0s/1mnlQ+X3nQnZM=
  - secure: LutO4R5bbEpGnpqFiZX2og4Y6cMIWhsPAWoyRyS4MrfBlNcU3IMpo5l6Mt0JY/9vU1lx86FDq904OhPG9oKumKKTzpJJPPRBhTYO8rq3ZgWKLwSLSQss7zCABtsB7TEKh/wuCpF+zXjYlrTwSs3QgMY1a2gWqATGf4QSju0gdah6kyHyxkw6FBXe6rl1sAq5RGhkyy9EaGvuTn91sSLdXsWIOIKcrJls/clAAzZe7r78oLFNwWZh6+EEodnMHbAgBZakOdXDNPrQMw9gKxomdaF3SdHewv6209h9MBCoABL7j2WCrqcD99TwrIPaerRPuVdvmHp3KO/p/e+3o+s0hfGJT2zYGqhLKOQ0HDZuxsCPQqBTBlCPvi+qWR6eTWx/yQxndEOhqdC239iT55blwEyT5Zj9HbRYGEy8RLKvl5jkMCYukWmEDZIGRr92Di70nCjY1OTiQ2fHAnzgy5ttHXp/uRt4ZAYAVd5TwY679TwsCN20a1CywDqQgOzMnoNQoS4PVdMFiJ81gaAw7QZU3oAZ2nQqcHgynzTMFRrTJNew0li8qD3NN70ZlH3yN19E+023GyebHr8nsljcnYsfNgBFg2Hvq9DGNzg/d5AFBbUOr2bu191XVdhseIvlRnUKaDT0YNPOuD3X7G5EjoiBM7TlfucHxW+WInUnevi023k=
