language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
  addons:
    apt:
      update: true
env:
  global:
  - secure: bIMCx/hvQzcOejpjUXnVKNWAeGdzT0eudsjhKjdxaaTBOMBbg/mtayxN9oxApwbiY+Q1JzWfyoJiBtQP/96UjvT0elwfWX6nkj113fWmUsASWDnqy7P+LWTAoDVBxOI6r5J+bM7eOR4S85BzLwyPZnOlm/WHwwojKRvR9HtB/4i5/z3MJ5IAoMTLH+9NBcaT3TVSOLQMNHNdJYj82Q5E4c0uPFWSD4WJTo8XTlr7OUcUy2BZKd+9EBhJ27ilraoNdS3D22VnIuTc/hB3nmQr3BaQQn+MAErpRC+s2tzYwXl3LOfAdQ1L6BjT1DJ9bHrg/ECEWwWa8u9kYdv0blyPJO+rCpr4l54Pn6r5ys0BYhkn0ir2aw/DvA2SFqYUb4bfOQIqLcUhtijlyJ4uuSkBHLs9uKug9dqPb7bLqoNI3WpnEmsjYLOIHJkoSlk0V/Qqb8FEI6VR7e/LqyPNlBeaC1FRHz6AHzEPJMljFb6NMlna1fwRBEGjXB0qnmUoM1MLtd61LtRCsgLhZ8VoA5gOQ/Alvn0ylH35azxOPXEkEYW2rmEuw4CPMx2lfhNd34RPlj1ynJ5WdykclAB2OzrNQYVKBsp1Wdro9U8h+pcHVuWJo8Yp7Kc4Sy7s4K9vIha56sdymEtqYOQ61qy/MKrpcCBxvHoPULcgSaav085FE7Y=
  - secure: QQaSCIjLa2LN6zqBLMc8SesrMvl5NJCc1sgwXWwiL/RxSzCqpSgh5i7c/Yg+D6Y6nwwTKQjVoahgQFrIrJnCynnpYD2MH0/ne0HxNlIrCqhFHEv2nbvoiVXdOvckDU95dseJxvMV7BdcGsJLBPNXyVzfDiTTxCrbJJ9ZJrV6SVBuHLXn4shwiqYtM6tKfkWrRLrh/qYYYnnfrbU2ef8SFZwDIWFmo6tbP/CNN1+PokZbC82KrQ1BMQMoxMT56O4qqjArDi4mxFrx2ydk96lbMcTG0n0IMW3xyFhfs4dYUuUnnfgsKh1wktXYGc2EJb5NN4wZerw/c7zs39Q0TCEh/o6LBy4wPD0RAi6ogtfnoBapc4JndjTp0FkgINjCqSXpL3GAUoD62jclA5Jn9bL8Ks1DzYscvcF6FJ1S/N2TeVVPb0b3R3LBLXUsm2JeJwbPHyRdlq44nqZWHgQ4DvS5EveObqbQDe/MtiohwDF8umDJi5/iqaw0Ez5pP+s22MSMh0AzJqflmdwMMfrlfndp6lpLM7FjDhFRvxmnrRtwok6EtYp6FLGCE2FTYJn5KLFZXMeBc1t4XSBNNWctvoJ49Klt4rObcTFwuZOltORK+kmYeIF2cIMMpvgnVaTX1q8poFdDcaHm/r2pbHmzGDjFLCtu/77cTp3SHc+W55FPmSs=
